[project]
name = "typepy_prelude"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "result>=0.17.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "PL", "RUF"]
ignore = [ "E703", "E701", "RUF001", "RUF002", "RUF003" ]
unfixable = [ "I001" ]
